wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.0
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681279158.423632
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 17
      - 23
      - 37
      4: 3.7.0
      5: 0.14.2
      6: 4.27.4
      8:
      - 5
