DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", 'colorjitter', 'gaussian_blur', "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.002
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 5e-4

TRAIN:
  PRINT_FREQ: 20
  TEST_FREQ: 5
  SAVE_FREQ: 50
  DIST_TRAIN: False

MODEL:
  BACKBONE:
    NAME: "RN50"

TRAINER:
  NAME: "baseline"
  PREC: "fp32"
  BASELINE:
    N_CTX: 4
    CTX_INIT: "a photo of a"  #
    FUSE: "cat"