DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 8
  TEST:
    BATCH_SIZE: 512
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  TEXT_AUG: "hand_crafted"

OPTIM:
  NAME: "adamw"
  LR: 0.0001
  LR_SCHEDULER: "cosine"
  WARMUP_TYPE: "linear"   # linear
  MAX_ITER: 12800
  WARMUP_ITER: 100
  WARMUP_LR: 1e-5

TRAIN:
  PRINT_FREQ: 200   # iters
  TEST_FREQ: 100  # val
  SAVE_FREQ: 12800
  DIST_TRAIN: False

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
  BONDER:
    DEPTH: 1
    NUM_Q: 32

TRAINER:
  NAME: "baseline_cattn_vocabloss_shembed_zsinit_lscale_wiseft"
  PREC: "fp32"
  BASELINE:
    N_CTX: 4
    CTX_INIT: "a photo of a"  #
    FUSE: "cat"